package com.szfp.biometric.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szfp.biometric.model.BiometricBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BIOMETRIC_BEAN".
*/
public class BiometricBeanDao extends AbstractDao<BiometricBean, Long> {

    public static final String TABLENAME = "BIOMETRIC_BEAN";

    /**
     * Properties of entity BiometricBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property FingerId = new Property(2, String.class, "fingerId", false, "FINGER_ID");
        public final static Property Model = new Property(3, byte[].class, "model", false, "MODEL");
    }


    public BiometricBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BiometricBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BIOMETRIC_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"FINGER_ID\" TEXT," + // 2: fingerId
                "\"MODEL\" BLOB);"); // 3: model
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BIOMETRIC_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BiometricBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String fingerId = entity.getFingerId();
        if (fingerId != null) {
            stmt.bindString(3, fingerId);
        }
 
        byte[] model = entity.getModel();
        if (model != null) {
            stmt.bindBlob(4, model);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BiometricBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String fingerId = entity.getFingerId();
        if (fingerId != null) {
            stmt.bindString(3, fingerId);
        }
 
        byte[] model = entity.getModel();
        if (model != null) {
            stmt.bindBlob(4, model);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BiometricBean readEntity(Cursor cursor, int offset) {
        BiometricBean entity = new BiometricBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fingerId
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3) // model
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BiometricBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFingerId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModel(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BiometricBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BiometricBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BiometricBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
