package com.szfp.biometric.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szfp.biometric.model.BiometricBean;

import com.szfp.biometric.greendao.BiometricBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig biometricBeanDaoConfig;

    private final BiometricBeanDao biometricBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        biometricBeanDaoConfig = daoConfigMap.get(BiometricBeanDao.class).clone();
        biometricBeanDaoConfig.initIdentityScope(type);

        biometricBeanDao = new BiometricBeanDao(biometricBeanDaoConfig, this);

        registerDao(BiometricBean.class, biometricBeanDao);
    }
    
    public void clear() {
        biometricBeanDaoConfig.clearIdentityScope();
    }

    public BiometricBeanDao getBiometricBeanDao() {
        return biometricBeanDao;
    }

}
